id: 5c91e61cc3bf40ef88abc1f5a7316ea6
initial_creation_type: ocr
source_metadata:
  volumes:
    c34b74b733744e95b0e841fc67f875ed:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: རྩོད་པ་བཟློག་པའི་འགྲེལ་པ།
      total_pages: 1605
      volume_number: 57
